// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJUcyFpBwb-8LxoMI7TlJO8taM-J8m3dw',
    appId: '1:606534019893:web:4ec4f44ffd969510fafa7c',
    messagingSenderId: '606534019893',
    projectId: 'samyati-399816',
    authDomain: 'samyati-399816.firebaseapp.com',
    storageBucket: 'samyati-399816.appspot.com',
    measurementId: 'G-9YJS0H544X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt5uUsrCo7092bYsVZrLvNuFpMt78OfSU',
    appId: '1:606534019893:android:bdb6bd9bd84f34b5fafa7c',
    messagingSenderId: '606534019893',
    projectId: 'samyati-399816',
    storageBucket: 'samyati-399816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkLmSbERh3NijE2PMqI2VRjLeFJNqkfhU',
    appId: '1:606534019893:ios:31af565191d7b0aafafa7c',
    messagingSenderId: '606534019893',
    projectId: 'samyati-399816',
    storageBucket: 'samyati-399816.appspot.com',
    androidClientId: '606534019893-la2bqlqkf8l4m1g6viq9kui285cvaf0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.samyati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkLmSbERh3NijE2PMqI2VRjLeFJNqkfhU',
    appId: '1:606534019893:ios:decd5544fb8e7efcfafa7c',
    messagingSenderId: '606534019893',
    projectId: 'samyati-399816',
    storageBucket: 'samyati-399816.appspot.com',
    androidClientId: '606534019893-la2bqlqkf8l4m1g6viq9kui285cvaf0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.samyati.RunnerTests',
  );
}
